name: Bug report
description: Report a reproducible issue or unexpected behavior in the project.
title: "[BUG] <short description>"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: input
    id: version
    attributes:
      label: Project Version
      description: What version or branch of the project are you using?
      placeholder: e.g. main branch, commit `abc123`, v0.1.0
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to trigger the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser or platform used (if applicable)
      placeholder: e.g. Chrome 125 on Windows 11

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Add screenshots or error logs to help diagnose the problem.
      render: shell
