name: Custom template
description: Open a general issue or ask a question.
title: "[CUSTOM] <short summary>"
labels: [question]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        This is a general-purpose issue template. Ask a question, raise a concern, or discuss something not covered by the other templates.

  - type: textarea
    id: content
    attributes:
      label: What's on your mind?
      description: Let us know what you're thinking or trying to do.
      placeholder: I have a question about...
